export const COMBOS_API_KEYS = {
  FETCH_COMBOS: 'FETCH_COMBOS' as const,
  FETCH_COMBOS_COUNT: ['FETCH_COMBOS', 'COUNT'] as const,
  FETCH_COMBO: 'FETCH_COMBO' as const,
  FETCH_COMBO_PRODUCTS: ['FETCH_COMBO', 'PRODUCTS'] as const,
};
