export const EXPENSE_CATEGORIES_API_KEYS = {
  FETCH_EXPENSE_CATEGORIES: 'FETCH_EXPENSE_CATEGORIES' as const,
  FETCH_EXPENSE_CATEGORIES_COUNT: ['FETCH_EXPENSE_CATEGORIES_COUNT', 'COUNT'] as const,
  FETCH_EXPENSE_CATEGORY: 'FETCH_EXPENSE_CATEGORY' as const
};