export const PRODUCT_API_KEYS = {
  FETCH_PRODUCTS: 'FETCH_PRODUCTS' as const,
  FETCH_PRODUCTS_COUNT: ['FETCH_PRODUCTS', 'COUNT'] as const,
  FETCH_PRODUCT: 'FETCH_PRODUCT' as const,
  FETCH_PRODUCT_DETAIL: ['FETCH_PRODUCT', 'DETAIL'] as const,
};
