export const STORE_API_KEYS = {
  FETCH_STORES: 'FETCH_STORES' as const,
  FETCH_STORES_COUNT: ['FETCH_STORES', 'COUNT'] as const,
  FETCH_STORE: 'FETCH_STORE' as const,
  FETCH_STORE_PRODUCTS: ['FETCH_STORE', 'PRODUCTS'] as const,
  FETCH_STORE_COMBOS: ['FETCH_STORE', 'COMBOS'] as const,
};
