export const USER_API_KEYS = {
  FETCH_CURRENT_USER: 'FETCH_CURRENT_USER' as const,
  FETCH_USERS: 'FETCH_USERS' as const,
  FETCH_USERS_COUNT: ['FETCH_USERS', 'COUNT'] as const,
  FETCH_USER: 'FETCH_USER' as const,
};
