export const WAREHOUSE_API_KEYS = {
  FETCH_WAREHOUSES: 'FETCH_WAREHOUSES' as const,
  FETCH_WAREHOUSES_COUNT: ['FETCH_WAREHOUSES', 'COUNT'] as const,
  FETCH_WAREHOUSE: 'FETCH_WAREHOUSE' as const,
};
