/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NoauthImport } from './routes/_no_auth'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as NoauthSignupImport } from './routes/_no_auth.signup'
import { Route as NoauthSigninImport } from './routes/_no_auth.signin'

// Create Virtual Routes

const AuthHomeLazyImport = createFileRoute('/_auth/home')()

// Create/Update Routes

const NoauthRoute = NoauthImport.update({
  id: '/_no_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthHomeLazyRoute = AuthHomeLazyImport.update({
  path: '/home',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth.home.lazy').then((d) => d.Route))

const NoauthSignupRoute = NoauthSignupImport.update({
  path: '/signup',
  getParentRoute: () => NoauthRoute,
} as any)

const NoauthSigninRoute = NoauthSigninImport.update({
  path: '/signin',
  getParentRoute: () => NoauthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_no_auth': {
      preLoaderRoute: typeof NoauthImport
      parentRoute: typeof rootRoute
    }
    '/_no_auth/signin': {
      preLoaderRoute: typeof NoauthSigninImport
      parentRoute: typeof NoauthImport
    }
    '/_no_auth/signup': {
      preLoaderRoute: typeof NoauthSignupImport
      parentRoute: typeof NoauthImport
    }
    '/_auth/home': {
      preLoaderRoute: typeof AuthHomeLazyImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([AuthHomeLazyRoute]),
  NoauthRoute.addChildren([NoauthSigninRoute, NoauthSignupRoute]),
])

/* prettier-ignore-end */
